# Generated by Django 4.1 on 2023-07-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonApp', '0002_cartitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_change_allowed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
