# Generated by Django 4.1 on 2023-07-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonApp', '0004_remove_user_password_change_allowed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='belong_to_category',
            new_name='belongs_to_category',
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=140, null=True),
        ),
    ]
