# Generated by Django 4.1 on 2023-07-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonApp', '0005_rename_belong_to_category_brand_belongs_to_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_change_allowed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
