# Generated by Django 4.1 on 2023-07-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazonApp', '0006_user_password_change_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='coins',
        ),
    ]
