# Generated by Django 4.1 on 2023-07-29 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazonApp', '0008_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='belongs_to_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazonApp.category'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
