# Generated by Django 4.1 on 2023-07-29 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazonApp', '0015_alter_product_category_name_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gallery1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='brand',
            name='belongs_to_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amazonApp.category'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=1040, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
