# Generated by Django 4.1 on 2023-07-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonApp', '0017_remove_product_gallery1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_change_allowed',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_change_allowed',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username_change_allowed',
            field=models.DateField(null=True),
        ),
    ]
