# Generated by Django 4.1 on 2023-07-30 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazonApp', '0021_alter_rate_rate_alter_rate_rated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
