# Generated by Django 4.1 on 2023-07-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonApp', '0023_alter_rate_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=1200),
        ),
    ]
