# Generated by Django 4.1 on 2023-07-31 23:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonApp', '0030_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Only letters are allowed.')]),
        ),
    ]
