# Generated by Django 4.1 on 2023-08-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonApp', '0032_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(default='USD', max_length=3, null=True),
        ),
    ]
