# Generated by Django 4.1 on 2023-08-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonApp', '0034_alter_user_currency_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN')], default='EUR', max_length=3, null=True),
        ),
    ]
