# Generated by Django 4.2.4 on 2023-08-25 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonApp', '0036_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bought_by_rec',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
