# Generated by Django 4.2.4 on 2023-09-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonApp', '0040_alter_opinion_reviewed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='text',
            field=models.TextField(max_length=1200),
        ),
    ]
