# Generated by Django 4.2.4 on 2023-09-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonApp', '0042_alter_opinion_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_change_allowed',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_change_allowed',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username_change_allowed',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
