# Generated by Django 4.2.4 on 2023-09-05 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonApp', '0044_alter_user_email_change_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_number',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_change_allowed',
            field=models.DateField(default=datetime.date(2023, 10, 6), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_change_allowed',
            field=models.DateField(default=datetime.date(2023, 10, 6), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username_change_allowed',
            field=models.DateField(default=datetime.date(2023, 10, 6), null=True),
        ),
    ]
