# Generated by Django 4.2.4 on 2023-09-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonApp', '0047_transaction_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='test_json',
            field=models.JSONField(null=True),
        ),
    ]
