# Generated by Django 4.2.4 on 2023-09-07 02:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazonApp', '0048_transaction_test_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='test_json',
        ),
        migrations.AlterField(
            model_name='opinion',
            name='rate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amazonApp.rate'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_change_allowed',
            field=models.DateField(default=datetime.date(2023, 10, 7), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_change_allowed',
            field=models.DateField(default=datetime.date(2023, 10, 7), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username_change_allowed',
            field=models.DateField(default=datetime.date(2023, 10, 7), null=True),
        ),
    ]
