# Generated by Django 4.2.4 on 2023-09-07 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazonApp', '0050_alter_opinion_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='rate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amazonApp.rate'),
        ),
    ]
